### ISSUE TITLE
Use progress bar percentage to set parameter when to mark videos as watched

### ISSUE THREAD

**Issue by EvNaverniouk** [EvNaverniouk/youtube-hide-watched#4]
We can use the progress bar YouTube gives us to set a threshold for when videos are watched. So we can add a button to control when we want videos to be marked as watched (ie. "Only marked video as watched if watched 10% or more).

**Comment by idelsink** [comment]
+1

**Comment by EvNaverniouk** [comment]
So I added this feature in the new version, but looks like YouTube does an awful job at tracking the progress. Most of my watched videos all show about 10% completed, even though I've watched it 100%. So I don't know if this will work as well as you expected:

![capture](https://cloud.githubusercontent.com/assets/226640/20644290/4534e26e-b3e4-11e6-979f-11866295fd69.PNG)

**Comment by idelsink** [comment]
I think the idea itself works perfect as expected. +1 for that. The poor and horrible implementation by youtube is just awful like you said. It always looks like they just have the youtube domain bound to their devel branch instead of a good release branch. :P
I guess if their gonna keep using this new progress thing, we're ready for it. And if not, well... Then it shows just how horrible youtube is and has become...
